### PR TITLE
randomize avatars

### PR DESCRIPTION
**Pull request by arpitsingla96**
the users with same name were getting same avatars

### CODE REVIEW

**Comment by apsdehal** [comment]
I would like to go with the previous solution since it provides me a unique avatar every time I use Jinora thus make me easily identifiable.

**Comment by arpit270896** [comment]
but it causes problem while uniquely identifying a user when two users with same nick come at same time. :confused:

**Comment by apsdehal** [comment]
It will have same probability as `Math.random` generating same numbers :p

**Comment by apsdehal** [comment]
Also the current solution incorporates username and links it to avatar. Thus current avatar is generated from the username itself.

**Comment by uttu357** [comment]
Closing this as we are not going forward with this.

**Pull request closed without merging**
