### PR TITLE
Added a new cat

### PR DESCRIPTION
**Pull request by nazywam**
[source](http://www.photos-public-domain.com/2012/10/15/orange-and-white-cat-face-close-up/)

### CODE REVIEW

**Comment by captn3m0** [comment]
Thanks!

I can't merge this right now, because merging to master would cause a redeploy. (and we'd lose history)

I'll do it as soon as the contest ends.

**Comment by Slind14** [comment]
contest?

**Comment by nazywam** [comment]
https://backdoor.sdslabs.co/competitions/backdoorctf15/dashboard

**Comment by captn3m0** [comment]
Just realized that we have a list of cats on server side as well. Will merge accordingly.

**Pull request merged**
