### PR TITLE
Adds user info

### PR DESCRIPTION
**Pull request by csoni111**
New command added : `!info <nick>`

Sample output:
Info for Wolf:
    _platform:_ Chrome 53.0.2785.143 on Ubuntu Chromium 64-bit
    _public ip:_ 103.37.201.75
    _local ip:_ 172.25.13.206

### CODE REVIEW

**Comment by tnmy44** [comment]
IMO, it makes more sense to track users' IPs on the backend, although we won't be able to get their private IP. Also I don't see any real use of tracking IPs, except for identifying spammers. But again, this can be very easily spoofed. @arpit270896 comments?

**Comment by csoni111** [comment]
I just wanted to find a way to uniquely identify a chat user. So that blocking him would be easier. Currently `!ban user <nick>` only bans the session, which can be very easily refreshed. So its not efficient.

**Comment by csoni111** [comment]
Also by getting the local ip of the user, we would be able to tell who exactly is that person if he is using iitr lan. Not sure about it though but at least we can tell which bhavan he belongs to.

**Comment by csoni111** [comment]
Currently this only works on Chrome and Firefox.
For other browsers it will give error in js and chat page won't load, so dont push these changes to the live version yet.
I have the updated code that works on all the browsers, will commit after I reach home on 21.

**Pull request merged**
